//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSR2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSREntities2 : DbContext
    {
        public DBSREntities2()
            : base("name=DBSREntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CuentaFacturacion> CuentaFacturacion { get; set; }
        public virtual DbSet<Feriado> Feriado { get; set; }
        public virtual DbSet<Hito> Hito { get; set; }
        public virtual DbSet<ModalidadProyecto> ModalidadProyecto { get; set; }
        public virtual DbSet<MotivoLicencia> MotivoLicencia { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Recurso> Recurso { get; set; }
        public virtual DbSet<RecursoLicencia> RecursoLicencia { get; set; }
        public virtual DbSet<RecursoProyecto> RecursoProyecto { get; set; }
        public virtual DbSet<ReporteEstado> ReporteEstado { get; set; }
        public virtual DbSet<TipoRecurso> TipoRecurso { get; set; }
    }
}
