//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public Proyecto()
        {
            this.Hito = new HashSet<Hito>();
            this.RecursoProyecto = new HashSet<RecursoProyecto>();
            this.ReporteEstado = new HashSet<ReporteEstado>();
        }
    
        public int IdProyecto { get; set; }
        public string Nombre { get; set; }
        public int IdCliente { get; set; }
        public int IdCuentaFacturacion { get; set; }
        public Nullable<System.DateTime> FechaInicioEstimada { get; set; }
        public Nullable<System.DateTime> FechaInicioReal { get; set; }
        public Nullable<System.DateTime> FechaFinEstimada { get; set; }
        public Nullable<System.DateTime> FechaFinReal { get; set; }
        public bool Activo { get; set; }
        public byte IdModalidadProyecto { get; set; }
        public Nullable<int> IdRecursoPL { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CuentaFacturacion CuentaFacturacion { get; set; }
        public virtual ICollection<Hito> Hito { get; set; }
        public virtual ModalidadProyecto ModalidadProyecto { get; set; }
        public virtual Recurso Recurso { get; set; }
        public virtual ICollection<RecursoProyecto> RecursoProyecto { get; set; }
        public virtual ICollection<ReporteEstado> ReporteEstado { get; set; }
    }
}
