//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.Proyecto = new HashSet<Proyecto>();
            this.RecursoLicencia = new HashSet<RecursoLicencia>();
            this.RecursoProyecto = new HashSet<RecursoProyecto>();
        }
    
        public int IdRecurso { get; set; }
        public string Nombre { get; set; }
        public byte IdTipoRecurso { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual TipoRecurso TipoRecurso { get; set; }
        public virtual ICollection<RecursoLicencia> RecursoLicencia { get; set; }
        public virtual ICollection<RecursoProyecto> RecursoProyecto { get; set; }
    }
}
