//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecursoLicencia
    {
        public int IdRecursoLicencia { get; set; }
        public int IdRecurso { get; set; }
        public byte IdMotivoLicencia { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string Observaciones { get; set; }
    
        public virtual MotivoLicencia MotivoLicencia { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
